spring:
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: jdbc:mysql://localhost:3306/where_to_travel
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    show-sql: true
